* Describing the International Standard Classification of Occupations (ISCO) in DDI 3.1
** Overview
This project uses the Data Documentation Initiative's DDI 3.1 XML standard to document the ISCO occupation codes.
*** ISCO
From [[http://en.wikipedia.org/wiki/International_Standard_Classification_of_Occupations][Wikipedia]]:
#+BEGIN_QUOTE
The International Standard Classification of Occupations (ISCO) is an International Labour Organization (ILO) classification structure for organizing information on labour and jobs. It is part of the international family of economic and social classifications of the United Nations.
#+END_QUOTE

The spreadsheet processed by this tool can be accessed [[http://ec.europa.eu/eurostat/ramon/download/classifications/xls/isco_88_com_de_en_fr.zip][here]].
*** DDI
Again from [[http://en.wikipedia.org/wiki/International_Standard_Classification_of_Occupations][Wikipedia]]:
#+BEGIN_QUOTE
The Data Documentation Initiative (DDI) is an international project to create a standard for information describing statistical and social science data. Begun in 1995, the effort brings together data professionals from around the world to develop the standard. The DDI specification, written in XML, provides a format for content, exchange, and preservation of information.
#+END_QUOTE
** Thanks
Joachim Wackerow originally [[http://www.ddialliance.org/node/394][marked up ISCO in DDI 3.0]]. His presentation about the project can be found [[http://www.edrs.mcgill.ca/IASSIST2007/presentations/E4(2).ppt][here]].
